spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to the Loans Microservice related to QA environment"
  contactDetails:
    name: "Dat Mai - QA Lead"
    email: "hiendat04-qa@gmail.com"
  onCallSupport:
    - (444) 123-4567
    - (444) 987-6543